sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    #point_cloud_topic: /camera/depth/color/points
    point_cloud_topic: /zed2/zed_node/point_cloud/cloud_registered
    max_range: 2.0
    frame_subsample: 1 #--
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 0.3
    max_update_rate: 1.0
    filtered_cloud_topic: filtered_cloud
